on:
  push

name: deno

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
    - uses: denolib/setup-deno@v2
    - shell: sh -ex {0}
      run: |
        echo $0
        
        echo 1
    - shell: /usr/bin/env sh -xc "cat '{0}' | deno run -"
      run: |
        import { bgBlue, red, bold, italic } from "https://deno.land/std@0.71.0/fmt/colors.ts";
        
        console.log(bgBlue(italic(red(bold("Hello world!")))));
    - shell: /usr/bin/env sh -xc "deno run {0}"
      run: |
        import { bgBlue, red, bold, italic } from "https://deno.land/std@0.71.0/fmt/colors.ts";

        console.log(bgBlue(italic(red(bold("Hello world!")))));
