on:
  push

name: deno

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
    - uses: denolib/setup-deno@v2
    - shell: sh -ex {0}
      run: |
        echo 1  
    - shell: deno run --allow-all {0}
      run: |
        // Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.
        import { bgBlue, red, bold, italic } from "https://deno.land/std@0.71.0/fmt/colors.ts";

        if (import.meta.main) {
          console.log(bgBlue(italic(red(bold("Hello world!")))));
        }
